### ISSUE TITLE
"disconnected from lightning peer"

### ISSUE THREAD

**Issue by sondreb** [ACINQ/phoenixd#117]
I have setup on a new server and it started giving these log entries after a few hours, is this normal and expected, or should I attempt to rectify somehow?

<img width="650" alt="image" src="https://github.com/user-attachments/assets/81dd83e8-ea13-4e3c-be25-37a2762f46b4">

**Comment by pm47** [comment]
Hello, there has been a major upgrade today, the LSP was restarted hence the disconnections.

Please upgrade phoenixd: https://github.com/ACINQ/phoenixd/releases/tag/v0.4.0

**Comment by sondreb** [comment]
Thanks for the quick feedback, I have upgraded and works fine. It also fixed the reconnect issue by restarting (I did that earlier today).
