### ISSUE TITLE
Inbound Liquidity depleted.

### ISSUE THREAD

**Issue by sixside** [ACINQ/phoenixd#131]
I was under the impression that channel liquidity should auto-adjust? Am I wrong? Seem my node isn't able to receive due to low inbound liquidity. How do I fix that?

    "channels": [
        {
            "state": "Normal",
            "balanceSat": 2799377,
            "inboundLiquiditySat": 203,
            "capacitySat": 2806721,
        }
    ],
    "chain": "mainnet",
    "blockHeight": 873809,
    "version": "0.4.2-24b817a"

**Comment by vincenzopalazzo** [comment]
>I was under the impression that channel liquidity should auto-adjust? Am I wrong? Seem my node isn't able to receive due to low inbound liquidity. How do I fix that?

What is your phoenixd configuration? e.g: the command line arguments?

**Comment by sixside** [comment]
This is what was suggested by the team:

Here is our recommendation to optimize your costs:
- use --auto-liquidity=10m (the highest value), it makes a real difference when mining fees are high

Any way to verify that setting is in place?

**Comment by pm47** [comment]
The user configuration is correct and the issue was not in phoenixd. There was a configuration issue yesterday on the LSP, preventing funding for some liquidity requests.
