### ISSUE TITLE
Add possibility to set seed and working directory via environment variables

### ISSUE THREAD

**Issue by prusnak** [ACINQ/phoenixd#3]
This would make it possible to simplify embedding `phoenixd` into other wallets such as Trezor Suite.

```
export PHOENIXD_SEED="abandon ..."
export PHOENIXD_WORKDIR="/path/to/workdir"
./phoenixd
```

When seed is provided via `PHOENIXD_SEED` it does not have to be stored in the `seed.dat` file because obviously it is managed by the caller.

Bonus points if `PHOENIXD_SEED` can be also defined as hex 256-bit number (64 hex digits = `[0-9][a-f]{64}`).

**Comment by tohrxyz** [comment]
+ 1 this is a real necessity for any further advancement with this

**Comment by prusnak** [comment]
Thanks!

**Comment by tsmith123** [comment]
I realise this issue is closed but is it possible to set the data directory via a flag too?

**Comment by pm47** [comment]
> I realise this issue is closed but is it possible to set the data directory via a flag too?

It's not trivial because the datadir contains the config file and other options depend on it. I don't think it's worth the complexity.

Just use this syntax, it's almost the same?
```
$ PHOENIX_DATADIR=/my/dir ./phoenixd
```
