### ISSUE TITLE
Feature Request: accounting export for all transactions

### ISSUE THREAD

**Issue by AngusP** [ACINQ/phoenixd#36]
Request to add an export transactions feature similar/identical to Phoenix mobile's CSV, with a date range for both incoming and outgoing transactions. Maybe also useful to include unpaid invoices, both expired and still open.

Currently as I understand it you can only get incoming transactions if you set and remembered elsewhere an `externalId`, or you would have to have stored all the payment hashes to be able to create an export using each `paymentId`

I think this is necessary for any merchant or individual to use phoenixd if their local tax and accounting rules require them to keep a record of transactions including donations.

**Comment by dongcarl** [comment]
Just to add to this: for `phoenixd`'s particular setup for automated liquidity, it would also be important for the "accounting export" to include information about whether funds:

> - go to your balance (normal scenario)
> - are used to purchase inbound liquidity immediately (once in a while)
> - are set aside to purchase inbound liquidity later (for small payments at bootstrapping).

Another good design goal could be that: from the "account export" ledger output (whatever you want to call it), one could easily arrive at the numbers given by `getbalance`

**Comment by Sjors** [comment]
I wrote a little tool that coverts this CSV to formats understood by bookkeeping software (currently just `CAMT.053`). It creates a fake IBAN number derived from the node ID and optionally converts all amounts to fiat based on historical exchange rates.
 
https://github.com/Sjors/btc-accounting/pull/7
