### ISSUE TITLE
API authentication request returns nothing

### ISSUE THREAD

**Issue by bitkarrot** [ACINQ/phoenixd#4]
According to the [documentation](https://phoenix.acinq.co/server/api#get-node-info) when attempting to access the API, with this example, and replacing the key in the example below `OjgxZWEy...2RlZmI=` with the Password for the http api from the config file ->  (default: reads from /Users/<username>/.phoenix/phoenix.conf), 

There is no response returned on the command line when entering the password from phoenix.conf

```
$ curl --location 'http://localhost:9740/getinfo' \
    --header 'Authorization: Basic OjgxZWEy...2RlZmI='

```

Are we supposed to modify the authorization password somewhere before passing it into following curl command? 

Please advise if we are using the command incorrectly or if we should be using the authorization key from somewhere else. 

Thanks in advance.

**Comment by bitkarrot** [comment]
Wait, does the API only work if there is a channel open?

**Comment by pm47** [comment]
Hi, try this:
`curl -u :<password> http://.../getinfo`

**Comment by bitkarrot** [comment]
ok thanks. @pm47

**Comment by jesuspirate** [comment]
nah I think @bitkarrot wanted to report the issue with the createinvoice api call instead: [doculink here](https://phoenix.acinq.co/server/api#receive-lightning-payment).

When running the command, it returns nothing...and it should return the following as described in the doc, but it doesn't:
```

{
    "amountSat": 100,
    "paymentHash": "f419207c9edde9021ebfb6bd0df6bd0a6606ecaf935357cc2f362e30835c3765",
    "serialized": "lntb1u1pjlsjnqpp57svjqly7mh5sy84lk67sma4apfnqdm90jdf40np0xchrpq6uxajscqpjsp592kp0fs2ssgpq9h54tsfaj5w34287v8fezgaw6cr56f076c05glq9q7sqqqqqqqqqqqqqqqqqqqsqqqqqysgqdq6d4ujqenfwfehggrfdemx76trv5mqz9grzjqwfn3p9278ttzzpe0e00uhyxhned3j5d9acqak5emwfpflp8z2cnflcyamh4dcuhwqqqqqlgqqqqqeqqjqnjpjvnv0p3wvwc6vhzkkgm8kl9r837x4p9qupk5ln5tqlm7prrlsy5xd8cf5agae64f53dvm9el0z5hvgcnta4stgmrg7zwfah0nqrqph4ts8l"
}
```

Let me know if I'm wrong. The getinfo returns something, just no channels mentioned.

**Comment by pm47** [comment]
The doc should be simplified to:
`curl -X POST -u :<password> -d 'description=my first invoice' -d 'amountSat=100' http://127.0.0.1:9740/createinvoice`

**Comment by bitkarrot** [comment]
In general, If the auth isn't working there should be an appropriate error message returned instead of nothing. 

Are the docs in a separate repo? Can we make PRs against it? 

Thanks in advance. @pm47

**Comment by dpad85** [comment]
The documentation page on the website has been updated, it should be easier to use now. Closing this issue, feel free to re-open if you still have problems.

**Comment by pm47** [comment]
> In general, If the auth isn't working there should be an appropriate error message returned instead of nothing.

Fixed in [4aa7f73](https://github.com/ACINQ/phoenixd/pull/6/commits/4aa7f73edf8630666d3067e1554b41d024d8e611)

> Are the docs in a separate repo? Can we make PRs against it?

Not currently, might change in the future

**Comment by bitkarrot** [comment]
@pm47 @dpad85 

I would still like to see a working example using the headers, if possible as I'm working on an integration with it right now

**Comment by bitkarrot** [comment]
Example python code that returns *401 ERROR*,  with no message

where it should return an invoice here: 

```py
import httpx
import os

# set HTTP_PWD environment var from default  ~/.phoenix/phoenix.conf
password = os.environ.get('HTTP_PWD')

url = 'http://127.0.0.1:9740/createinvoice'
data = {'description': 'my first invoice', 'amountSat': '100'}

response = httpx.post(url, auth=(':', password), data=data)

print(response.status_code)
print(response.text)
```


The curl command, does work however: 

```
$ curl -X 'POST' 'http://localhost:9740/createinvoice' \
    -u :phoenixd_api_password \
    -d 'description=my first invoice' \
    -d 'amountSat=100' \
    -d 'externalId=foobar'

```

Usage docs here: https://www.python-httpx.org/

Screenshot here: 

<img width="599" alt="Screenshot 2024-03-25 at 1 32 59 PM" src="https://github.com/ACINQ/phoenixd/assets/73979971/39a5d900-b106-4eea-aed5-272d3c408048">
