### ISSUE TITLE
external connection to Phoenixd

### ISSUE THREAD

**Issue by EdoardoSnodato** [ACINQ/phoenixd#61]
nobody wallet mobile (Zeus, Bluewallet ...) can connect directly to phoenixd server ?

**Comment by dpad85** [comment]
No, phoenixd just like Phoenix Wallet directly connects to the ACINQ node, so that you don't have to manage your channels or your [liquidity](https://phoenix.acinq.co/server/auto-liquidity) manually or configure your node.
