### ISSUE TITLE
Issue with 0.2.0 docs

### ISSUE THREAD

**Issue by tsmith123** [ACINQ/phoenixd#64]
Your docs appear to be incorrect here:

The `invoice` param should be `offer` (and a desc of "BOLT 12 Offer)" and you need to add a mention of the `message` param.

![image](https://github.com/ACINQ/phoenixd/assets/7639854/d16123f9-05d0-4826-8029-86bec644b379)

**Comment by dpad85** [comment]
Thanks for reporting this issue. It is now fixed.
