### ISSUE TITLE
phoenixd 0.3.2 doesn't work in Fedora 40

### ISSUE THREAD

**Issue by ktecho** [ACINQ/phoenixd#89]
When trying to use `phoenixd` in `Fedora 40`, I get this message:

```
./phoenixd: error while loading shared libraries: [libcrypt.so](https://libcrypt.so/).1: cannot open shared object file: No such file or directory
```

It works without problems in Ubuntu 24.04.

**Comment by sstone** [comment]
This seems to be specific to Fedora (see https://fedoraproject.org/wiki/Changes/FullyRemoveDeprecatedAndUnsafeFunctionsFromLibcrypt), the fix is to install the `libxcrypt-compat` package:
```sh
sudo dnf install libxcrypt-compat
```
