### ISSUE TITLE
401 Failure with httpx

### ISSUE THREAD

**Issue by bitkarrot** [ACINQ/phoenixd#9]
Example python code that returns *401 ERROR*,  with no message

where it should return an invoice here: 

```py
import httpx
import os

# set HTTP_PWD environment var from default  ~/.phoenix/phoenix.conf
password = os.environ.get('HTTP_PWD')

url = 'http://127.0.0.1:9740/createinvoice'
data = {'description': 'my first invoice', 'amountSat': '100'}

response = httpx.post(url, auth=(':', password), data=data)

print(response.status_code)
print(response.text)
```

The curl command, does work however: 

```
$ curl -X 'POST' 'http://localhost:9740/createinvoice' \
    -u :phoenixd_api_password \
    -d 'description=my first invoice' \
    -d 'amountSat=100' \
    -d 'externalId=foobar'

```

Usage docs here: https://www.python-httpx.org/

Screenshot here: 

<img width="599" alt="Screenshot 2024-03-25 at 1 32 59 PM" src="https://github.com/ACINQ/phoenixd/assets/73979971/39a5d900-b106-4eea-aed5-272d3c408048">

Is it possible to use headers with phoenixd?

**Comment by bitkarrot** [comment]
it would be nice to add 

https://ktor.io/docs/bearer.html#configure-provider

in addition to where it has just basic here

https://github.com/ACINQ/phoenixd/blob/c7be8371174247ea92b34edb15ac6e9c2633aff0/src/commonMain/kotlin/fr/acinq/lightning/bin/Api.kt#L77-L87

**Comment by pm47** [comment]
> response = httpx.post(url, auth=(':', password), data=data)

Remove the colon, it just separates username:password in the curl command: `response = httpx.post(url, auth=('', password), data=data)`
